// <auto-generated />
using System;
using EnviromentalApp.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnviromentalApp.Database.Migrations
{
    [DbContext(typeof(EnviromentalAppDbContext))]
    partial class EnviromentalAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnviromentalApp.Database.Models.AirQualityMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("No2")
                        .HasColumnType("float");

                    b.Property<double>("PM10")
                        .HasColumnType("float");

                    b.Property<double>("PM25")
                        .HasColumnType("float");

                    b.Property<double>("S02")
                        .HasColumnType("float");

                    b.Property<int>("sensorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AirQualityMeasurements");
                });

            modelBuilder.Entity("EnviromentalApp.Database.Models.Sensor", b =>
                {
                    b.Property<int>("sensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sensorId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firmwareVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("measurementFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sensorId");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("EnviromentalApp.Database.Models.Ticket", b =>
                {
                    b.Property<int>("ticketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ticketId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sensorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ticketDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ticketId");

                    b.ToTable("SensorTicket");
                });

            modelBuilder.Entity("EnviromentalApp.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnviromentalApp.Database.Models.WaterQualityMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("EC")
                        .HasColumnType("float");

                    b.Property<double>("IE")
                        .HasColumnType("float");

                    b.Property<double>("NitrateN02")
                        .HasColumnType("float");

                    b.Property<double>("NitrateN03")
                        .HasColumnType("float");

                    b.Property<double>("Phosphate")
                        .HasColumnType("float");

                    b.Property<int>("sensorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WaterQualityMeasurements");
                });

            modelBuilder.Entity("EnviromentalApp.Database.Models.WeatherMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<int>("sensorId")
                        .HasColumnType("int");

                    b.Property<int>("windDirection")
                        .HasColumnType("int");

                    b.Property<double>("windSpeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeatherMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
